spring:
  datasource:
    url: jdbc:mysql://192.168.0.150:3306/a_myw?autoReconnect=true
    username: dbadmin
    password: 2017admin*QMX
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true
  freemarker:
        template-loader-path: ["classpath:/templates/", "classpath:/castemplates/"]

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      local: false
      repositories:
        enable: true


server:
  servlet:
    context-path: /
  port: 8080
  compression:
    enabled: true
  use-forward-headers: true

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
    default-statement-timeout: 2000
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath*:mapper/**/*Mapper.xml

pagehelper:
  helper-dialect: mysql

